
name: Deploy Docs
on:
  push:
    tags:
      - "*"
    branches:
      - add_docs

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Install coreutils
        run: brew install coreutils

      - name: Build Docs
        run: echo "alias cp=gcp" >> ~/.bashrc && mkdir MembraneRTC/docs && xcodebuild docbuild -scheme MembraneRTC -destination generic/platform=iOS OTHER_DOCC_FLAGS="--transform-for-static-hosting --output-path docs --hosting-base-path membrane-webrtc-ios"

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: MembraneRTC/docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}