
name: Run lint & tests
on: [push]

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: brew install swift-format xcbeautify

      - name: Run formatter
        run: swift-format format -i -r ./MembraneRTC/Sources/**/*.swift --configuration swift-format-config.json

      - name: Run lint
        run: swift-format lint -r ./MembraneRTC/Sources/**/*.swift --configuration swift-format-config.json

      - name: Run tests
        run: xcodebuild test -scheme MembraneVideoroomDemo -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.5' -workspace 'MembraneVideoroomDemo.xcworkspace' -sdk iphonesimulator | xcbeautify
